CREATE TABLE place (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  place_id VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  address VARCHAR(500),
  lat FLOAT(53),
  lng FLOAT(53),
  createdDate DATETIME2 DEFAULT SYSDATETIME(),
  createdBy VARCHAR(30) DEFAULT "SYSTEM",
  updatedDatet DATETIME2 DEFAULT SYSDATETIME(),
  updatedBy VARCHAR(30) DEFAULT "SYSTEM"
);
